apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gin-tattoo
  namespace: prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - aladiatattoo.com.br
      secretName: gin-tattoo-prod-tls
  rules:
    - host: aladiatattoo.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gin-tattoo
                port:
                  name: http
