apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tattoo-db-credentials
  namespace: prod
spec:
  encryptedData:
    DATABASE_URL: AgAxhe92QOy4CpUNu8Kfu8dNqvZawcF8rkCzmFt+xtwJclmXU5SCNPf3Ywwxx0dsgq/DkLx06NQDD2LsXIH5z9kDRnpOea6SwLkdXGfPErGGB+xTIgBgh5/9jXeP+Ay2eVsOeUZPiEKVFjk7wYUrEE2IXMnskEmF/jDE2UfOKDD/pyCcULYU/5lFB1clneG9RcMx6KXMlcHmMpGWaSq5gRU5R5iYbNexMjKYI9C7oe/WoLUW2XOxcxs8eNAV7XkYk1LkUmyHeNx0/NUwxKOgpSent3KRmCnMf0yg2u5bkULK3vWsGT0lbHRtR6H87lo172q46zJdoPQNmbJa3OXI65Iwg+36EXqOckJ8RMq1ED+ZLw/QKd0a94CZBrjiQKdleqEjQa015B4/+lGRjfzE+urzfZejQCdBeinFkc25m7twbkXTlHMAoYPiwDbhLCiS+DRFzd0Y6r92kxnLWhrV4o+259TafsGMXsbu6FoB9wcFiRMrZ0WdrMPS/c/5k9HTGCEefuhLHA91fdxSUuKETbhjDaoI77RppvtvYzYZc5QbO+V9BJMWVP3WBNzRzfW/SVx8Mfd1cWzxNV/uM8sDM6RIjIC2UOWMA+itlTxjmWCgVpeGIdbiJ20ZzNlwd8mQlMEgH5PvDaRKFD+T1VWFjGTYZjq/llM+BfQaFxt6Ts+Dlk9olm/2sQOF6o+DxiWZziL2p1klxnb6GvhQdTU+Iq36uirrAea8NYnCYSatLAFcRnEzm+hNHpNPE1W8ipkZltvJCPFqiOW2nEjjkf8mO3c69qZ/qNWcoAwkZuCZTgh1XwRBcwu4GE6o
  template:
    metadata:
      creationTimestamp: null
      name: tattoo-db-credentials
      namespace: prod

