apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tattoo-db-credentials
  namespace: prod
spec:
  encryptedData:
    DATABASE_URL: AgBWUEAA+sC5oI9Y9BXjKHG2jOhFIFFeyIdTBktVHaxR1CLVBGDFtW4Q1KiDi6dOe5hT4UHY3ynS9mKdXOhhJH1ENBwS9fvGwmZeVIAjfASseX53/URRgIbMYCQ1pl7HsVzBj0ywhDCTaex90QBm0OfDAvL+mGxRrfhO8akuRE75+wSwAcB1/i1F3eGysZa0DadwHGlVcOJBSQQpBnRFXiSN6iLScD3TZF3n5+Ml0O3nILWZbEsrVQu7VEdFj4i4TBzk8sgPTobTs/F+TgjWIPgS9Rp1/NusF51u+fHnXAM/7rkOoTWlnas2WIOsFVTNDCA/xRT6HxwQBwt3D+nSeA3+egtCvv0qP550erggz0x8wh1VzAI3gzi9T0Kvr9nU2ZB6fKgx9l6JqmSwqTXOLQeQNUtiJmi3sh2XmNkViHZ5dSxX9lzcWAWZYtjJ38MUEd7xonAGJ63BiGgoteR9NfscKF/MnLCSqYl9nsdzLFuagKZqqLHppUDxrDz0Fa7JmAbLQHBmYz1L9TnHv5ROBXghbEgO6rXy8Eea0QZLRVfd3OQbhvhGuGHDDkgSZy8AnHe0TyaJEbzO/7BxvXtX+9urgdht6dA042G2jgwXkI3VNBc1oqozjZAckr8YwAMGkrw7KNZ8Zhxfymr60n/ZvC79qo3+/ZyaeInJsDIAyipUPKEmyDZc+svI0RjKHymiz8ywF6rIZhS+/lrpOChHdpmgCX7pM/JJ5OasywE0/K1h+rn5Ds54Cyz2aO+nZUERbnSXS86bYkcaRU9AANP/S3MwV+2xbbJrMOOTPR4P4r0IUfgIrilY
  template:
    metadata:
      creationTimestamp: null
      name: tattoo-db-credentials
      namespace: prod

