apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tattoo-db-credentials
  namespace: prod
spec:
  encryptedData:
    DATABASE_URL: AgAvfIq6n1j+tuC+OUxUdYye+lD865Pp4gads7K0e9wKMVQZweYhF8+HZ9HVQDTKLxIfSUePIUUjrmTndYXgfRNpDt+FuElLxb0KXq4f5vm7Dkcc6aIU709ywnXSYu9vc9bKTpF4fFtbpc4uFerc4habD0hsqtk4Sel6NrJC2V8xtJaXY/0ibC3Vl2Mue8WjFkjW0oHJRFiml7ClNe1otLrrruIxVfiZt1aQKCJsp9geJ2uNLQLZ7EaZoo/PbDkq5q5G48G2LujReNezNITQHecRBbG2R/8QIO7b/cvqxjxgDIeQ8zUjub3O6H1DlrIPUARCdB+dD+/ncuKf8YE5pICIK3+ZUWRsaBjJOgWYRj3VAvrt93vI+KWjXPu1DmndgLufoyiPD5PZVSAPNeVyMLKULkZmLIw57ipprqZKXrL7ibNMOsMReQUzGfozntb37XtLMhfOnTeace1j1uB0DqwfN/7UbbdWIhgV4lnuEWXN9pl3xjuuievXQXXZfhBUuzNitBGnVOEDYHDqTVn/Cm2nH7YeuBZms0jKoTVeXzxR+9S6Zv0k6BsI5K+V1zuYx/WHiJTK3+34rnlXl1uQ7/trMeCS1EUKdNcMqnDvRDxjrtu/csUEYggYA63xaLM9J0FNbHA+Kr40KsaXyncAspcYGAmtKIKa7Hzxx/7whponCenKNrOfduh4znvV3qKR6FonxTivGgRhKe8qceQkc6J/enCO9QIK+Yp1Qpx82Tgp8y7Veb3ycfGSAqXRWLMiuz21okN5IewDCw86/LRDQg79MwaZuha7YhIIWv/rrfYZ/8oAx0QTLg==
  template:
    metadata:
      creationTimestamp: null
      name: tattoo-db-credentials
      namespace: prod

