apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tattoo-db-credentials
  namespace: homolog
spec:
  encryptedData:
    DATABASE_URL: AgBjEAhSYrp8KFySvkiJMeRRjDYm6OHJyC/CZ7/5W4N3Kg1roKEuUuDp34oiPNxY70XI9TSiRuT00nyH0xpZBYY9wDP/mKIReycjt62z5XqS8QbMjYeSOceER97vF8qlBp6uhGPTowx8c1fUdd+LM7R66MvLmWYxzy8MOlr508nmz8PBNYcw6HWv25aOZJUAvGEbRU+VQnFpmkjxPqKFNDoUIjiYigQICFkHwepsb0BjslZ39fUlnS2UG1Qt+oJ0dXdnnHvSxu284QuG4CmcvcDzN6oUUXIMCExjI/SbJcEJwSHlgX288wE7bk8eDpr0FFAsfhl73viB80pCVcMXV54cwO8ffub38mu0XabJH7nyOAEhEKGCz+18ceukb687JlglbhSMFq9PhBGYJMPJU139rN0FhGIf5tHsNprXiCPhN4JSxY0fUaK3QlRsTnGt3MPzTO2Ppas+S/ghmjfEgZinWiithr7ye6+mWC8M5TPw1B6N/A1Dh7l2dUDvzmWCfH47agdCpBYlU/2LFp9ZDHWR3WRB2PawgX5mD1J5KYB+G+nlbK/BHrDqlxzuJEspu8Vm0s2SkaedEQaGtfYizJKbgHo86qGSPk2fMyJ0ORX0ytplmMoelsD1hDOC1VhYTFFVXoKr55p51zaGm8csqSOeCNviJSejMgJcaOF8yAHUR0SPGk+bU6QBHRNU26tDFyMv//EZw6wk3ueTg6xTDe+42VY9fMpTNxRyJ0i/7V+yv3IGmyRXWaou6uQLbM5lYue1bnCRIF2aKNG8YQwrrnTj5CNYj/YZMoqp+oS6fkAmp/ptpAdwIJQX
  template:
    metadata:
      creationTimestamp: null
      name: tattoo-db-credentials
      namespace: homolog

