apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tattoo-db-credentials
  namespace: homolog
spec:
  encryptedData:
    DATABASE_URL: AgCOkXDuShXHjNXCzl5rVNBMQmPNnxabeWyZLJ0lF9nWGle8WDOyU4nybjDbl0FCK/H2yc4kQ+JhRImT8g+R7W++qO4DxqCcZv70Ig5Ww9vdgubxaSk3DaM/X7dUStrPz83JeqnSD5umEjX7f4CKbUsFVsiV1soZi/HMYey0C7IDPsBgxny4lkVguYTOpPZp7OvPWVVgEsKRKW245iCrmTbJAVfa5gNdbb7nl5r3crhA3A7wF562pzr0lhv7lisQXVjuMpqyC18lc0GJgGPtpCV/9hSsf1tWy2XbwZ7+U7D13BOjCqib9EWx/uYGk3wbENaUwYpaGRz2LpMSIPJMXp8i3vKzUwHbQvtRmpoN1J8gg0btK3YaRSsBULmdEErKlX6WSD78QKlm+One7y3xmoYTan49UFX1ULyjfCygoAAehW4L851LdEUeNhxCYYKmecnxL3LmX4KA2/pme71FdHcaI4qXf8UtgTwDuMCzFgkvPjuidnnfU9IcwSJ8ey87MteiQztG/AARP6EF0YnBchTwgme5ZuTwJM/hTgpieIscvBzOrbZohvLc19HgPPyblRjZv/QZiwxWzneDC7Q7jDt/GjtLb6xkcYMSz1T/yMJ8WhyOndCGw8uQagjceoIlAdxxGVPRIA/XiE1xkNHMUG44K3cZ8EiqsxvMX3a1REsv+FvnkhdVOwrPNpxMPMX3YBc/QTNKmP8G24kyWzNKw6Vws4w6SJGC4GwitUIkaZxbrT7fhMb1sB5sDolG6XghD1UfMezuQF9cmQeFia8fR9tmj+HiWMrGV5RGmCfJydbIOxTLlPnilA==
  template:
    metadata:
      creationTimestamp: null
      name: tattoo-db-credentials
      namespace: homolog

