apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tattoo-db-credentials
  namespace: homolog
spec:
  encryptedData:
    DATABASE_URL: AgCU8nhfqnEJ6exiJM8kekSYv5tvbBSMGJqAyqMwj6Bm7NBVmPK6XNOe/NaiCCzxoXAFqAsoR5j6xHap4qnVMobMY7Z/Q2ZUHaqUVEvt/UiNuaUjwY8t1IDOs3p45vM+ruMsbHfTJX/w4jE5eolMZ4y8DM3ls0Vy5W+tT4/ili9Hq3FRr0T6m9ITPt7Iz3Wtf54iTGTILWsEgu/PsFHg68mxLC3BtMry+TDFNceLoPtW+TMLBSZovPIE7vyomwxrEajMszm+Nv+bwGQVoxbjef7iZywhDzvQ/xeqXCV2X1kM6QR+xa2YBj56r0O6pse5P/H+j1ZxogRtGTyBluVzhzAQExNMtfWxpsfDKN8nofLhYf13+x8YvTjLepq7V1cBS84fkKKAD5vcoEhzCi9/Tca5MmmEMnzwmANUfzf5KiinfTu65CJ5EPqgG7bUqSbb2ey3Deg42AGdGHf/I1s1biT9e6ssoLIxcuoVpGdWgR0RdonQdXQzkLBiahD8cddz9Mx4DgFS+VuvplVExssDMBnKsGhLk/PpXl6T/ycJEFIJ5+7AHTxmtDkgLNYVmQb5Vnvcqe72sTZxZdgjEBub5AlZy7ZVawCjU3cJNKgynUPk5T6qIpc6im7CCXMhXcFN5rs6P/w+RNniS9yHrsff1meQD6RuhXArYa0O+KoNBd0f1zMo3vZc7r5vXSrxbfp2oLoogcDBv9rdANycnqIhGD13ijdWfXmmUGhhX9YyoJDZnvd+4d+MGwGmiUzgzTqGtvpULnoXa0n4UtiNuV5/uK5EPjItNx+YjbOtDKjSss3JKgrR3Wl/
  template:
    metadata:
      creationTimestamp: null
      name: tattoo-db-credentials
      namespace: homolog

